import numpy as np
arr = np.arange(1,11)
print(arr)
print(arr + arr)
print(arr - arr)
print(arr * arr)
print(1/arr)
print(arr**2)
sqrt_root = np.sqrt(arr)
print(sqrt_root)
ex = np.exp(arr)
print(ex)
max = np.max(arr)
print(max)

sin = np.sin(arr)
print(sin)
log = np.log(arr)
print(log)